# This is a basic workflow to help you get started with Actions

name: SMProcessing-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master testing-on-smprocessing]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Build Docker
      run: |
        docker pull qgis/qgis:latest
        docker run -d --name qgis-testing-environment -v ${{ github.workspace }}:/tests_directory -e DISPLAY=:99 qgis/qgis:latest
        sleep 10
      
    - name: Setup Qgis, and enable plugin
      run: |
        docker exec -it qgis-testing-environment sh -c "qgis_setup.sh SMProcessing"
        # Link the plugin to the tests_directory
        docker exec  -it qgis-testing-environment sh -c "rm -f /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SMProcessing"
        docker exec -it qgis-testing-environment sh -c "ln -s /tests_directory/ /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SMProcessing"
    
    - name: Run Tests
      run: docker exec -it qgis-testing-environment sh -c "cd /tests_directory && qgis_testrunner.sh SMProcessing.test.test_geometries"
